spring:
    datasource:
        url: jdbc:mysql://localhost:3306/asm_java6
        username: root
        password: 
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:            
            ddl-auto: update
