spring:
    datasource:
        url: jdbc:mysql://localhost:3306/authentication
        username: root
        password: 
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:            
            show-sql: true
            ddl-auto: update
